---
- name: Hello World Sample
  hosts: all
  collections:
    - geerlingguy.php_roles
    
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
  roles:
    - php
    - role: php-version
      vars:
        php_version: '7.3'
    
      
   
