---
- name: Hello World Sample
  hosts: ul-bip-ts-asm01.ul.ca
  connection: local
  collections:
    - f5networks.f5_modules
    
  vars:
    bip_server: "{{ ansible_host }}"
    bip_port: 443
    bip_user: "{{ ansible_user }}"
    bip_password: "{{ ansible_password }}"
    bip_validate_certs: false
    bip_transport: rest
    bip_timeout: 120
    bip_method: POST
    bip_delay: 30
    bip_retries: 10
    bip_provider:
       server: "{{ bip_server }}"
       server_port: "{{ bip_port }}"
       user: "{{ bip_user }}"
       password: "{{ bip_password }}"
       validate_certs: "{{ bip_validate_certs }}"
       transport: "{{ bip_transport }}"
       auth_provider: tmos
    as3_show: base
    as3_showhash: true
    as3_async: false
    
  tasks:
    - name : BIGIP Get ConfigSync Status 
      bigip_command:
        provider: "{{ bip_provider }}"
        commands:
           - "tmsh show /cm sync-status"
      register: tmsh_data

    - set_fact:
        configsync: {
           color: "{{ tmsh_data.stdout_lines[0][3] | regex_replace('Color (.*)$', '\\1') | trim }}",
           status: "{{ tmsh_data.stdout_lines[0][4] | regex_replace('Status (.*)$', '\\1') | trim }}",
           mode: "{{ tmsh_data.stdout_lines[0][5] | regex_replace('Mode (.*)$', '\\1') | trim }}",
           summary: "{{ tmsh_data.stdout_lines[0][6] | regex_replace('Summary (.*)$', '\\1') | trim }}"
        }

    - debug:
        msg: "{{ configsync }}"
     
   
      
   
