- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: hostname
      shell: hostnamectl
      register: info
    - name: info
      debug:
        vars: info
