---
- name: Hello World Sample
  hosts: all
  
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: Set time
      vars:
        timesync_ntp_servers:
          - hostname: ntp.ulaval.ca
            iburst: yes
          - hostname: ntp2.ulaval.ca
            iburst: yes
      roles:
        name: rhel-system-roles.timesync
      
   
