---
- name: Hello World Sample
  hosts: all
  vars:
    timesync_ntp_servers:
      - hostname: ntp.ulaval.ca
        iburst: yes
      - hostname: ntp2.ulaval.ca
        iburst: yes
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: hostname
      shell: hostnamectl
      register: shell_info
    - debug:
        msg: "{{ shell_info.stdout_lines }}"      
    - name: Set timesync
      roles:
        - linux-system-roles.timesync
      
   
