---
- name: Hello World Sample
  hosts: all
  # import_roles: rhel-system-roles.timesync
  
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - import_role:
        name: rhel-system-roles.timesync
  
    
      
   
