---
- name: UL Host Information
  hosts: all
  
  tasks:
    - name : "Get Host Information"
      shell: "hostnamectl"
      register: shell_data
   
    - debug:
        msg: "{{ shell_data.stdout_lines }}"
