---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: hostname
      shell: hostnamectl
      register: shell_info
    - debug:
        msg: "{{ shell_info.stdout_lines }}"      
    - name: Set timesync
      vars:
        timesync_ntp_servers:
          - hostname: ntp.ulaval.ca
            iburst: yes
          - hostname: ntp2.ulaval.ca
            iburst: yes
      roles:
        - linux-system-roles.timesync
      
   
