---
- name: Hello World Sample
  hosts: all
  
  tasks:
    - name : "BIGIP Get ConfigSync Status"
      bigip_command:
        provider: "{{ bip_provider }}"
        commands:
           - "tmsh show /cm sync-status"
      register: tmsh_data
      delegate_to: localhost

    - set_fact:
        configsync: {
           color: "{{ tmsh_data.stdout_lines[0][3] | regex_replace('Color (.*)$', '\\1') | trim }}",
           status: "{{ tmsh_data.stdout_lines[0][4] | regex_replace('Status (.*)$', '\\1') | trim }}",
           mode: "{{ tmsh_data.stdout_lines[0][5] | regex_replace('Mode (.*)$', '\\1') | trim }}",
           summary: "{{ tmsh_data.stdout_lines[0][6] | regex_replace('Summary (.*)$', '\\1') | trim }}"
        }

    - debug:
        msg: "{{ configsync }}"
     
   
      
   
