- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: hostname
      shell: hostnamectl
      register: shell_info
    - debug:
        msg: "{{ shell_info }}"
      
   
